# Generated by Django 4.2.7 on 2023-12-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairshare_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published testing'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
