# Generated by Django 4.2.7 on 2023-12-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairshare_backend', '0002_user_alter_blogpost_pub_date_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
